# Generated by Django 4.1.2 on 2022-10-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='nombre',
        ),
    ]
