# Generated by Django 4.1.2 on 2022-10-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=32, verbose_name='Nombre'),
        ),
    ]
