# Generated by Django 4.1.2 on 2022-10-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0002_alter_genero_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='codigo',
            field=models.CharField(help_text='XXXX-YYYY', max_length=16, unique=True, verbose_name='Código'),
        ),
    ]
