# Generated by Django 4.1.2 on 2022-10-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16, unique=True, verbose_name='Ubicación')),
                ('pais', models.CharField(blank=True, help_text='País de Origen', max_length=16, verbose_name='País')),
                ('web', models.URLField(blank=True, max_length=256, verbose_name='Página Web')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombre'],
            },
        ),
    ]
