# Generated by Django 4.1.2 on 2022-10-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16, unique=True, verbose_name='Ubicación')),
                ('codigo', models.CharField(help_text='XXXX', max_length=8, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, help_text='¿Donde está ubicado?', max_length=256, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre', 'codigo'],
            },
        ),
    ]
