# Generated by Django 4.1.2 on 2022-10-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(help_text='XXXX-YYYY', max_length=16, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=32, unique=True, verbose_name='Ubicación'),
        ),
    ]
